package com.warfront.client;

import com.warfront.Warfront;
import com.warfront.client.model.UnitGeometry;
import net.minecraft.client.renderer.entity.player.PlayerRenderer;
import net.minecraft.client.resources.PlayerSkin;
import com.warfront.registry.WFRegistry;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;

@EventBusSubscriber(modid = Warfront.MODID, bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public final class ClientSetup {
    private ClientSetup() {}

    /** F8: the Test Panel, when test mode is on. */
    public static final net.minecraft.client.KeyMapping TEST_PANEL = new net.minecraft.client.KeyMapping(
            "key.warfront.test_panel", com.mojang.blaze3d.platform.InputConstants.Type.KEYSYM,
            org.lwjgl.glfw.GLFW.GLFW_KEY_F8, "key.categories.warfront");

    /** J: recall home during a raid warning or attack. */
    public static final net.minecraft.client.KeyMapping RECALL = new net.minecraft.client.KeyMapping(
            "key.warfront.recall", com.mojang.blaze3d.platform.InputConstants.Type.KEYSYM,
            org.lwjgl.glfw.GLFW.GLFW_KEY_J, "key.categories.warfront");

    @SubscribeEvent
    public static void onKeys(net.neoforged.neoforge.client.event.RegisterKeyMappingsEvent event) {
        event.register(TEST_PANEL);
        event.register(RECALL);
    }

    @SubscribeEvent
    public static void onGuiLayers(net.neoforged.neoforge.client.event.RegisterGuiLayersEvent event) {
        event.registerAboveAll(Warfront.id("siege_banner"), com.warfront.client.ui.SiegeBanner::render);
        event.registerAbove(net.neoforged.neoforge.client.gui.VanillaGuiLayers.HOTBAR, Warfront.id("combat_hud"),
                com.warfront.client.ui.CombatHud::render);
    }

    @SubscribeEvent
    public static void onRegisterRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(WFRegistry.SOLDIER.get(), SoldierRenderer::new);
        event.registerEntityRenderer(WFRegistry.ADVISOR_ENTITY.get(), AdvisorRenderer::new);
        event.registerEntityRenderer(WFRegistry.MERCHANT.get(), net.minecraft.client.renderer.entity.WanderingTraderRenderer::new);
    }

    @SubscribeEvent
    public static void onRegisterLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
        // Imp Impaler and Firecaster, the demon player and worker gear, all generated by tools/units.py.
        UnitGeometry.all().forEach((id, definition) -> {
            if (!id.equals("demon_player")) event.registerLayerDefinition(WFModelLayers.of(id), definition);
        });
        event.registerLayerDefinition(WFModelLayers.DEMON_PLAYER, UnitGeometry::demon_player);
    }

    @SubscribeEvent
    public static void onAddLayers(EntityRenderersEvent.AddLayers event) {
        for (PlayerSkin.Model skin : event.getSkins()) {
            if (event.getSkin(skin) instanceof PlayerRenderer renderer) {
                renderer.addLayer(new DemonPlayerLayer(renderer, event.getEntityModels()));
            }
        }
    }
}
