package com.warfront.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * GENERATED by tools/units.py from the unit model specs. Do not edit by hand: change the spec and
 * re-run the script, which also repaints the matching textures.
 */
public final class UnitGeometry {
    private UnitGeometry() {}

    /** The imp body. */
    public static LayerDefinition imp() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p0 = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(76, 0).addBox(-3.5F, -7F, -3.5F, 7F, 7F, 7F).texOffs(98, 33).addBox(-3.5F, -5F, -4.5F, 7F, 1F, 1F),
                PartPose.offsetAndRotation(0F, 1F, -1.5F, 0F, 0F, 0F));
        PartDefinition p1 = p0.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(40, 33).addBox(-2.5F, -1.5F, -1F, 5F, 2F, 1F),
                PartPose.offsetAndRotation(0F, 0F, -3.5F, 0F, 0F, 0F));
        PartDefinition p2 = p0.addOrReplaceChild("goatee", CubeListBuilder.create().texOffs(56, 28).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, 0.5F, -4.2F, 0.25F, 0F, 0F));
        PartDefinition p3 = p0.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(60, 28).addBox(-4F, -1.5F, -0.5F, 4F, 3F, 1F),
                PartPose.offsetAndRotation(-3.5F, -4F, 0.5F, 0F, -0.45F, -0.3F));
        PartDefinition p4 = p3.addOrReplaceChild("ear_r_tip", CubeListBuilder.create().texOffs(114, 33).addBox(-2F, -0.5F, -0.5F, 2F, 1F, 1F),
                PartPose.offsetAndRotation(-4F, -1F, 0F, 0F, 0F, -0.5F));
        PartDefinition p5 = p0.addOrReplaceChild("horn_c", CubeListBuilder.create().texOffs(70, 28).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(0F, -7F, 0.5F, -0.6F, 0F, 0F));
        PartDefinition p6 = p0.addOrReplaceChild("horn_r1", CubeListBuilder.create().texOffs(106, 19).addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(-1.8F, -7F, -0.5F, -0.45F, 0F, -0.35F));
        PartDefinition p7 = p0.addOrReplaceChild("horn_r2", CubeListBuilder.create().texOffs(74, 28).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-3F, -6.5F, 1.5F, -0.7F, 0F, -0.65F));
        PartDefinition p8 = p0.addOrReplaceChild("horn_r3", CubeListBuilder.create().texOffs(52, 33).addBox(-0.5F, -2F, -0.5F, 1F, 2F, 1F),
                PartPose.offsetAndRotation(-2F, -6F, 3F, -1.1F, 0F, -0.4F));
        PartDefinition p9 = p0.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(78, 28).mirror().addBox(0F, -1.5F, -0.5F, 4F, 3F, 1F).mirror(false),
                PartPose.offsetAndRotation(3.5F, -4F, 0.5F, 0F, 0.45F, 0.3F));
        PartDefinition p10 = p9.addOrReplaceChild("ear_l_tip", CubeListBuilder.create().texOffs(120, 33).mirror().addBox(0F, -0.5F, -0.5F, 2F, 1F, 1F).mirror(false),
                PartPose.offsetAndRotation(4F, -1F, 0F, 0F, 0F, 0.5F));
        PartDefinition p11 = p0.addOrReplaceChild("horn_l1", CubeListBuilder.create().texOffs(110, 19).mirror().addBox(-0.5F, -4F, -0.5F, 1F, 4F, 1F).mirror(false),
                PartPose.offsetAndRotation(1.8F, -7F, -0.5F, -0.45F, 0F, 0.35F));
        PartDefinition p12 = p0.addOrReplaceChild("horn_l2", CubeListBuilder.create().texOffs(88, 28).mirror().addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).mirror(false),
                PartPose.offsetAndRotation(3F, -6.5F, 1.5F, -0.7F, 0F, 0.65F));
        PartDefinition p13 = p0.addOrReplaceChild("horn_l3", CubeListBuilder.create().texOffs(56, 33).mirror().addBox(-0.5F, -2F, -0.5F, 1F, 2F, 1F).mirror(false),
                PartPose.offsetAndRotation(2F, -6F, 3F, -1.1F, 0F, 0.4F));
        PartDefinition p14 = root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
        PartDefinition p15 = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(104, 0).addBox(-3F, 0F, -1.5F, 6F, 9F, 3F).texOffs(60, 19).addBox(-2.5F, 9F, -1.5F, 5F, 3F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 0F, 0.2F, 0F, 0F));
        PartDefinition p16 = p15.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(0, 37).addBox(-15F, -0.5F, -0.5F, 15F, 1F, 1F).texOffs(0, 0).addBox(-15F, 0.5F, 0F, 15F, 19F, 0F),
                PartPose.offsetAndRotation(-1.5F, 1.5F, 1.5F, 0.25F, 0.6F, 0.85F));
        PartDefinition p17 = p16.addOrReplaceChild("wing_r_claw", CubeListBuilder.create().texOffs(92, 28).addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F),
                PartPose.offsetAndRotation(-15F, 0F, 0F, 0F, 0F, -0.9F));
        PartDefinition p18 = p16.addOrReplaceChild("wing_r_finger1", CubeListBuilder.create().texOffs(30, 0).addBox(-0.5F, 0F, -0.5F, 1F, 18F, 1F),
                PartPose.offsetAndRotation(-6F, 0.5F, 0F, 0F, 0F, -0.18F));
        PartDefinition p19 = p16.addOrReplaceChild("wing_r_finger2", CubeListBuilder.create().texOffs(68, 0).addBox(-0.5F, 0F, -0.5F, 1F, 16F, 1F),
                PartPose.offsetAndRotation(-11F, 0.5F, 0F, 0F, 0F, 0.05F));
        PartDefinition p20 = p15.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(32, 37).mirror().addBox(0F, -0.5F, -0.5F, 15F, 1F, 1F).mirror(false).texOffs(34, 0).mirror().addBox(0F, 0.5F, 0F, 15F, 19F, 0F).mirror(false),
                PartPose.offsetAndRotation(1.5F, 1.5F, 1.5F, 0.25F, -0.6F, -0.85F));
        PartDefinition p21 = p20.addOrReplaceChild("wing_l_claw", CubeListBuilder.create().texOffs(96, 28).mirror().addBox(-0.5F, -3F, -0.5F, 1F, 3F, 1F).mirror(false),
                PartPose.offsetAndRotation(15F, 0F, 0F, 0F, 0F, 0.9F));
        PartDefinition p22 = p20.addOrReplaceChild("wing_l_finger1", CubeListBuilder.create().texOffs(64, 0).mirror().addBox(-0.5F, 0F, -0.5F, 1F, 18F, 1F).mirror(false),
                PartPose.offsetAndRotation(6F, 0.5F, 0F, 0F, 0F, 0.18F));
        PartDefinition p23 = p20.addOrReplaceChild("wing_l_finger2", CubeListBuilder.create().texOffs(72, 0).mirror().addBox(-0.5F, 0F, -0.5F, 1F, 16F, 1F).mirror(false),
                PartPose.offsetAndRotation(11F, 0.5F, 0F, 0F, 0F, -0.05F));
        PartDefinition p24 = p15.addOrReplaceChild("tail_1", CubeListBuilder.create().texOffs(76, 19).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 3F),
                PartPose.offsetAndRotation(0F, 10.5F, 1.5F, -0.55F, 0F, 0F));
        PartDefinition p25 = p24.addOrReplaceChild("tail_2", CubeListBuilder.create().texOffs(88, 19).addBox(-1.5F, -1.5F, 0F, 3F, 3F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.15F, 0F, 0F));
        PartDefinition p26 = p25.addOrReplaceChild("tail_3", CubeListBuilder.create().texOffs(114, 19).addBox(-1F, -1F, 0F, 2F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.35F, 0F, 0F));
        PartDefinition p27 = p26.addOrReplaceChild("tail_4", CubeListBuilder.create().texOffs(0, 28).addBox(-1F, -1F, 0F, 2F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.45F, 0F, 0F));
        PartDefinition p28 = p27.addOrReplaceChild("tail_5", CubeListBuilder.create().texOffs(10, 28).addBox(-1F, -1F, 0F, 2F, 2F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.5F, 0F, 0F));
        PartDefinition p29 = p28.addOrReplaceChild("tail_6", CubeListBuilder.create().texOffs(100, 28).addBox(-0.5F, -0.5F, 0F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.5F, 0F, 0F));
        PartDefinition p30 = p29.addOrReplaceChild("tail_7", CubeListBuilder.create().texOffs(108, 28).addBox(-1F, -1F, 0F, 2F, 2F, 2F),
                PartPose.offsetAndRotation(0F, 0F, 3F, 0.3F, 0F, 0F));
        PartDefinition p31 = p30.addOrReplaceChild("tail_tuft", CubeListBuilder.create().texOffs(60, 33).addBox(-1.5F, -3F, 0F, 3F, 3F, 0F).texOffs(100, 19).addBox(0F, -3F, -1F, 0F, 3F, 3F),
                PartPose.offsetAndRotation(0F, -1F, 1F, -0.6F, 0F, 0F));
        PartDefinition p32 = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(0, 19).addBox(-1F, -1F, -1F, 2F, 7F, 2F),
                PartPose.offsetAndRotation(-4.2F, 2.5F, 0F, 0F, 0F, 0.12F));
        PartDefinition p33 = p32.addOrReplaceChild("forearm_r", CubeListBuilder.create().texOffs(8, 19).addBox(-1F, 0F, -1F, 2F, 7F, 2F),
                PartPose.offsetAndRotation(0F, 6F, 0F, -0.3F, 0F, -0.08F));
        PartDefinition p34 = p33.addOrReplaceChild("hand_r", CubeListBuilder.create().texOffs(66, 33).addBox(-1F, 0F, -1F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 7F, 0F, 0F, 0F, 0F));
        PartDefinition p35 = p34.addOrReplaceChild("hand_r_claw0", CubeListBuilder.create().texOffs(20, 28).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(-0.8F, 1F, -0.6F, -0.45F, 0F, -0.2F));
        PartDefinition p36 = p34.addOrReplaceChild("hand_r_claw1", CubeListBuilder.create().texOffs(24, 28).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(0F, 1F, -0.6F, -0.45F, 0F, 0F));
        PartDefinition p37 = p34.addOrReplaceChild("hand_r_claw2", CubeListBuilder.create().texOffs(28, 28).addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F),
                PartPose.offsetAndRotation(0.8F, 1F, -0.6F, -0.45F, 0F, 0.2F));
        PartDefinition p38 = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(16, 19).mirror().addBox(-1F, -1F, -1F, 2F, 7F, 2F).mirror(false),
                PartPose.offsetAndRotation(4.2F, 2.5F, 0F, 0F, 0F, -0.12F));
        PartDefinition p39 = p38.addOrReplaceChild("forearm_l", CubeListBuilder.create().texOffs(24, 19).mirror().addBox(-1F, 0F, -1F, 2F, 7F, 2F).mirror(false),
                PartPose.offsetAndRotation(0F, 6F, 0F, -0.3F, 0F, 0.08F));
        PartDefinition p40 = p39.addOrReplaceChild("hand_l", CubeListBuilder.create().texOffs(74, 33).mirror().addBox(-1F, 0F, -1F, 2F, 1F, 2F).mirror(false),
                PartPose.offsetAndRotation(0F, 7F, 0F, 0F, 0F, 0F));
        PartDefinition p41 = p40.addOrReplaceChild("hand_l_claw0", CubeListBuilder.create().texOffs(32, 28).mirror().addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F).mirror(false),
                PartPose.offsetAndRotation(0.8F, 1F, -0.6F, -0.45F, 0F, 0.2F));
        PartDefinition p42 = p40.addOrReplaceChild("hand_l_claw1", CubeListBuilder.create().texOffs(36, 28).mirror().addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F).mirror(false),
                PartPose.offsetAndRotation(0F, 1F, -0.6F, -0.45F, 0F, 0F));
        PartDefinition p43 = p40.addOrReplaceChild("hand_l_claw2", CubeListBuilder.create().texOffs(40, 28).mirror().addBox(-0.5F, 0F, -0.5F, 1F, 4F, 1F).mirror(false),
                PartPose.offsetAndRotation(-0.8F, 1F, -0.6F, -0.45F, 0F, -0.2F));
        PartDefinition p44 = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(44, 19).addBox(-1F, 0F, -1F, 2F, 5F, 2F),
                PartPose.offsetAndRotation(-1.5F, 12F, 0F, -0.6F, 0F, 0F));
        PartDefinition p45 = p44.addOrReplaceChild("shin_r", CubeListBuilder.create().texOffs(32, 19).addBox(-0.75F, 0F, -0.75F, 1.5F, 6F, 1.5F),
                PartPose.offsetAndRotation(0F, 5F, 0F, 1.1F, 0F, 0F));
        PartDefinition p46 = p45.addOrReplaceChild("ankle_r", CubeListBuilder.create().texOffs(44, 28).addBox(-0.75F, 0F, -0.75F, 1.5F, 3F, 1.5F),
                PartPose.offsetAndRotation(0F, 6F, 0F, -0.8F, 0F, 0F));
        PartDefinition p47 = p46.addOrReplaceChild("foot_r", CubeListBuilder.create().texOffs(82, 33).addBox(-1F, -0.5F, -1F, 2F, 1F, 2F),
                PartPose.offsetAndRotation(0F, 3F, 0F, 0.3F, 0F, 0F));
        PartDefinition p48 = p47.addOrReplaceChild("toe_r0", CubeListBuilder.create().texOffs(116, 28).addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(-0.7F, 0F, -1F, 0.25F, 0F, 0F));
        PartDefinition p49 = p47.addOrReplaceChild("toe_r1", CubeListBuilder.create().texOffs(0, 33).addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0F, 0F, -1F, 0.25F, 0F, 0F));
        PartDefinition p50 = p47.addOrReplaceChild("toe_r2", CubeListBuilder.create().texOffs(8, 33).addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F),
                PartPose.offsetAndRotation(0.7F, 0F, -1F, 0.25F, 0F, 0F));
        PartDefinition p51 = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(52, 19).mirror().addBox(-1F, 0F, -1F, 2F, 5F, 2F).mirror(false),
                PartPose.offsetAndRotation(1.5F, 12F, 0F, -0.6F, 0F, 0F));
        PartDefinition p52 = p51.addOrReplaceChild("shin_l", CubeListBuilder.create().texOffs(38, 19).mirror().addBox(-0.75F, 0F, -0.75F, 1.5F, 6F, 1.5F).mirror(false),
                PartPose.offsetAndRotation(0F, 5F, 0F, 1.1F, 0F, 0F));
        PartDefinition p53 = p52.addOrReplaceChild("ankle_l", CubeListBuilder.create().texOffs(50, 28).mirror().addBox(-0.75F, 0F, -0.75F, 1.5F, 3F, 1.5F).mirror(false),
                PartPose.offsetAndRotation(0F, 6F, 0F, -0.8F, 0F, 0F));
        PartDefinition p54 = p53.addOrReplaceChild("foot_l", CubeListBuilder.create().texOffs(90, 33).mirror().addBox(-1F, -0.5F, -1F, 2F, 1F, 2F).mirror(false),
                PartPose.offsetAndRotation(0F, 3F, 0F, 0.3F, 0F, 0F));
        PartDefinition p55 = p54.addOrReplaceChild("toe_l0", CubeListBuilder.create().texOffs(16, 33).mirror().addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F).mirror(false),
                PartPose.offsetAndRotation(0.7F, 0F, -1F, 0.25F, 0F, 0F));
        PartDefinition p56 = p54.addOrReplaceChild("toe_l1", CubeListBuilder.create().texOffs(24, 33).mirror().addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F).mirror(false),
                PartPose.offsetAndRotation(0F, 0F, -1F, 0.25F, 0F, 0F));
        PartDefinition p57 = p54.addOrReplaceChild("toe_l2", CubeListBuilder.create().texOffs(32, 33).mirror().addBox(-0.5F, -0.5F, -2.5F, 1F, 1F, 3F).mirror(false),
                PartPose.offsetAndRotation(-0.7F, 0F, -1F, 0.25F, 0F, 0F));
        return LayerDefinition.create(mesh, 128, 128);
    }
}
